# MbedTLS is built from the pinned source, never a machine-specific DLL.
set(MbedTLS_FOUND TRUE)
set(MBEDTLS_FOUND TRUE)
set(MBEDTLS_INCLUDE_DIR "${mbedtls_SOURCE_DIR}/include")
set(MBEDTLS_INCLUDE_DIRS "${mbedtls_SOURCE_DIR}/include")
set(MBEDTLS_LIBRARY mbedtls)
set(MBEDX509_LIBRARY mbedx509)
set(MBEDCRYPTO_LIBRARY mbedcrypto)
set(MBEDTLS_LIBRARIES mbedtls mbedx509 mbedcrypto)
if(NOT TARGET MbedTLS::MbedTLS)
  add_library(MbedTLS::MbedTLS INTERFACE IMPORTED)
  set_target_properties(MbedTLS::MbedTLS PROPERTIES INTERFACE_LINK_LIBRARIES "mbedtls;mbedx509;mbedcrypto" INTERFACE_INCLUDE_DIRECTORIES "${mbedtls_SOURCE_DIR}/include")
endif()
if(NOT TARGET MbedTLS::mbedtls)
  add_library(MbedTLS::mbedtls ALIAS mbedtls)
  add_library(MbedTLS::mbedx509 ALIAS mbedx509)
  add_library(MbedTLS::mbedcrypto ALIAS mbedcrypto)
endif()
